### ISSUE TITLE
`Prefix_Adapter`& `MHAdapter_Layer` in the `petl/petl_factory.py` seems to be not used

### ISSUE THREAD

**Issue by Doragd** [jxhe/unify-parameter-efficient-tuning#13]
"Adapter" is not defined. 

```python
class Prefix_Adapter(nn.Module):
    def __init__(self, args, config):
        super().__init__()
        self.prefix = Prefix(args, config)
        self.adapters = Adapter(args, config) # "Adapter" is not defined 

    def forward(self, bsz, nsamples=1, device="cuda"):
        prefix = self.prefix(bsz, nsamples, device)
        adapters = self.adapters(bsz)

        for ii, dic in enumerate(adapters):
            for key, value in dic.items():
                prefix[ii][key] = value
        return prefix
```

**Comment by Doragd** [comment]
* `embed_dim` is not defined: https://github.com/jxhe/unify-parameter-efficient-tuning/blob/master/src/transformers/models/roberta/modeling_roberta.py#L203
* `src_len` is not defined: https://github.com/jxhe/unify-parameter-efficient-tuning/blob/master/src/transformers/models/roberta/modeling_roberta.py#L349
* `src_len` is not defined: https://github.com/jxhe/unify-parameter-efficient-tuning/blob/master/src/transformers/models/roberta/modeling_roberta.py#L350

**Comment by jxhe** [comment]
Thank you for capturing these oversights! We just fixed them
