### ISSUE TITLE
How the initialization of Prefix affects the performance? 

### ISSUE THREAD

**Issue by Doragd** [jxhe/unify-parameter-efficient-tuning#14]
I would like to know how the initialization of Prefix affects the performance in the following situation.
* situation 1:  the official implementation
```python
class Prefix(nn.Module):
    def __init__(...):
        ...
class PETLEncModel(PretrainedModel):
    def __init__(...):
         ...
        self.pretrained_model = pretrained_model
        self.prompt_model = Prefix(...)
        ...
```

* situation 2: my re-implementation
```python
class Prefix(nn.Module):
    def __init__(...):
        ...
class PETLEncModel(RobertaPretrainedModel):
    def __init__(...):
        ...
        self.roberta = RobertaModel(config) # the details of RobertaModel (with adapter) copy from your implementation
        self.prompt_model = Prefix(...)
        self.init_weights() # how the init_weights affects?
    
```

**Comment by jxhe** [comment]
I am not sure, I think we just use the pytorch default initialization of Prefix

**Comment by Doragd** [comment]
Thanks a lot.

**Comment by Doragd** [comment]
@jxhe I have another issue with the initialization. 
In the example: `exps/run_glue.sh`, the initialization of 'lora' is applied in the `Adapter_Layer` using the following code snippet.
```
if init_option == "bert":
    self.apply(init_bert_weights)
elif init_option == "lora":
    with torch.no_grad():
        nn.init.kaiming_uniform_(self.down_proj.weight, a=math.sqrt(5))
        nn.init.zeros_(self.up_proj.weight)
        nn.init.zeros_(self.down_proj.bias)
        nn.init.zeros_(self.up_proj.bias)
```
However, when calling the `AutoModelForSequenceClassification.from_pretrained(...)`, the `Adapter_Layer`, which is not contained in the pre-trained structures, will be re-initialization by the `self.init_weights()`. 

Thus, **the initialization of 'lora' has got overridden and actually not working.**

I don't know if I understand correctly, could you help me to check it?

**Comment by jxhe** [comment]
The re-initialization will skip all the parameter names with the string "ef_", i.e., all the added modules:

https://github.com/jxhe/unify-parameter-efficient-tuning/blob/56de3b21e5fb70cecb5f4a120a9c069281ccbc27/src/transformers/models/roberta/modeling_roberta.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L1346

**Comment by Doragd** [comment]
@jxhe  THANkS SO MUCH!
