### ISSUE TITLE
Question about your parameter budget

### ISSUE THREAD

**Issue by EchoShao8899** [jxhe/unify-parameter-efficient-tuning#15]
Hi,

Thank you so much for opening the source code. I'm trying to use your MAM Adapter on Roberta and has a question about your parameter budget.

I'm following the config in `exps/run_glue.sh` but found the number of trainable parameters much larger than expected. More specifically, I use the following code snippet to calculate trainable parameters and the result is 46783200.
```python
sum([param.nelement() if param.requires_grad else 0 for param in model.parameters()])
```

I investigated your code and found in `petl/petl_factory.py/Prefix`, those modules for calculating `temp_dict['encoder_decoder']` and `temp_dict['encoder']` are unnecessary for Roberta, so I excluded them. However, I still have 16000160 parameters, and the detailed information is as follows (`module - require_grads - nelement`):
```shell
pretrained_model.roberta.embeddings.word_embeddings.weight False 38603520
pretrained_model.roberta.embeddings.position_embeddings.weight False 394752
pretrained_model.roberta.embeddings.token_type_embeddings.weight False 768
pretrained_model.roberta.embeddings.LayerNorm.weight False 768
pretrained_model.roberta.embeddings.LayerNorm.bias False 768
pretrained_model.roberta.encoder.layer.0.attention.self.query.weight False 589824
pretrained_model.roberta.encoder.layer.0.attention.self.query.bias False 768
pretrained_model.roberta.encoder.layer.0.attention.self.value.weight False 589824
pretrained_model.roberta.encoder.layer.0.attention.self.value.bias False 768
pretrained_model.roberta.encoder.layer.0.attention.self.key.weight False 589824
pretrained_model.roberta.encoder.layer.0.attention.self.key.bias False 768
pretrained_model.roberta.encoder.layer.0.attention.output.dense.weight False 589824
pretrained_model.roberta.encoder.layer.0.attention.output.dense.bias False 768
pretrained_model.roberta.encoder.layer.0.attention.output.LayerNorm.weight False 768
pretrained_model.roberta.encoder.layer.0.attention.output.LayerNorm.bias False 768
pretrained_model.roberta.encoder.layer.0.intermediate.dense.weight False 2359296
pretrained_model.roberta.encoder.layer.0.intermediate.dense.bias False 3072
pretrained_model.roberta.encoder.layer.0.output.dense.weight False 2359296
pretrained_model.roberta.encoder.layer.0.output.dense.bias False 768
pretrained_model.roberta.encoder.layer.0.output.LayerNorm.weight False 768
pretrained_model.roberta.encoder.layer.0.output.LayerNorm.bias False 768
pretrained_model.roberta.encoder.layer.0.output.ef_ffn_adapter.down_proj.weight True 12288
pretrained_model.roberta.encoder.layer.0.output.ef_ffn_adapter.down_proj.bias True 16
pretrained_model.roberta.encoder.layer.0.output.ef_ffn_adapter.up_proj.weight True 12288
pretrained_model.roberta.encoder.layer.0.output.ef_ffn_adapter.up_proj.bias True 768
pretrained_model.roberta.encoder.layer.0.ef_ffn_adapter.down_proj.weight True 12288
pretrained_model.roberta.encoder.layer.0.ef_ffn_adapter.down_proj.bias True 16
pretrained_model.roberta.encoder.layer.0.ef_ffn_adapter.up_proj.weight True 12288
pretrained_model.roberta.encoder.layer.0.ef_ffn_adapter.up_proj.bias True 768

...... (layer.1 - layer.11 are the same with layer.0)

pretrained_model.classifier.dense.weight False 589824
pretrained_model.classifier.dense.bias False 768
pretrained_model.classifier.out_proj.weight False 2304
pretrained_model.classifier.out_proj.bias False 3
prompt_model.wte.weight True 12288
prompt_model.control_trans.0.weight True 614400
prompt_model.control_trans.0.bias True 800
prompt_model.control_trans.2.weight True 14745600
prompt_model.control_trans.2.bias True 18432
```

From your paper, you said that the MAM Adapter only costs 0.5% parameters of the original LM, so I'm confused if I misunderstood something or did anything wrong.

Thanks for your time and your help!

**Comment by jxhe** [comment]
Hi,

The MLP reparameterization parameters (i.e. the parameters in `prompt_model` such  as `control_trans`) of prefix are not counted towards the added parameters because they can be discarded at test time after training. As the paper explains, prefix tuning adds `2ld` parameters per layer. This is how our paper as well as other related papers in this direction count the *added parameters* of prefix tuning.

Another way to think of this is that the MLP network is a reparameterization of the prefix vectors, thus it doesn't really add capacity but is like an optimization trick first discovered by the prefix tuning paper.

**Comment by EchoShao8899** [comment]
Thank you so much for your quick reply!

Just want to double check: The reparameterization trick requires the MLP network to be trainable during the training time but can be discarded in the inference time. That means we have to tune more than 0.5% parameters in the training but only add 0.5% of the model capacity in the inference (i.e. 'tunable parameters' mentioned in Table 11 in the paper Appendix actually analyzes the model capacity increase in the inference, to nicely optimize the model, we actually need more tunable parameters in the training stage). Is this understanding correct? 
> The MLP reparameterization parameters (i.e. the parameters in prompt_model such as control_trans) of prefix are not counted towards the added parameters because they can be discarded at test time after training.

**Comment by jxhe** [comment]
Yes your understanding is correct, and sorry I think the "tunable parameters" is not a vey accurate term when involving with prefix tuning.

**Comment by EchoShao8899** [comment]
Thank you for clarifying this. It's very helpful!

Close this issue since I'm clear now.
